Fix bug crash relaunch on Android
sailing-yacht-research-foundation/client-sdk-react-native pull request #11
Opened 2022-03-30 08:23 UTC by Levis-ScopicSoftware

Remove load lazy activity and local broadcast that is cause retain instance of activity when press back and relaunch app.

2022-03-30 09:44 UTC, RSMNYS requested changes

2022-03-30 09:44 UTC, RSMNYS commented on react-native-syrf-client/android/src/main/java/com/reactnativesyrfclient/SyrfClientModule.kt
> +    if (currentActivity != null) {
Please don't do many levels of if. It's hard to understand. Better to have the structure more flat. If (activity === null) {return false}. And so on

2022-03-30 09:44 UTC, RSMNYS commented on react-native-syrf-client/android/src/main/java/com/reactnativesyrfclient/SyrfClientModule.kt
> +      getMapOrNull(params, KEY_PERMISSION_REQUEST_CONFIG)?.let { permissionRequestParams ->
here we can extract permissionConfigBuilder into a separate function with all configs.

2022-03-30 09:44 UTC, RSMNYS commented on react-native-syrf-client/android/src/main/java/com/reactnativesyrfclient/SyrfClientModule.kt
> +    if (currentActivity != null) {
Same here with the flat structure.

2022-03-30 09:44 UTC, RSMNYS commented on react-native-syrf-client/android/src/main/java/com/reactnativesyrfclient/SyrfClientModule.kt
> +    if (currentActivity != null) {
and here

2022-03-31 07:27 UTC, Levis-ScopicSoftware commented
@RSMNYS  I have fixed comments, please help me check again. Thanks

2022-04-08 19:16 UTC, RSMNYS commented
Just a question, why do you think it's crashing. Also have you tried your fix and make sure it behaves differently?

2022-04-08 19:26 UTC, merged